name: rowad_hrag
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.17
  route_transitions: ^2.0.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  carousel_slider: ^5.0.0
  video_player: ^2.7.1
  cached_network_image: ^3.3.0
  animated_custom_dropdown: ^3.1.1
  flutter_launcher_icons: ^0.14.3
  animate_do: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/1024.png"
  adaptive_icon_background: "#0EBE7F"
  macos:
    generate: true
    image_path: "assets/images/1024.png"

  flutter_lints: ^5.0.0

flutter:
  generate: true # Add this line


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/adds/
    - assets/images/products/
    - assets/images/categories/
    - assets/icons/
    - assets/fonts/cairo/