name: rowad_hrag
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_easyloading: ^3.0.5
  flutter_svg: ^2.0.17
  route_transitions: ^2.0.1
  dartz: ^0.10.1
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  carousel_slider: ^5.0.0
  video_player: ^2.7.1
  cached_network_image: ^3.3.0
  animated_custom_dropdown: ^3.1.1
  animate_do: ^4.2.0
  skeletonizer: ^1.4.3
  flutter_launcher_icons: ^0.14.3
  icons_launcher:
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  flutter_rating_bar: ^4.0.1
  hive: ^2.2.3
  file_picker: ^10.2.0
  image_picker: ^1.1.2
  bot_toast: ^4.1.3
  lottie: ^3.3.1
#  palette_generator: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

icons_launcher:
  image_path: "assets/images/1024.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/adds/
    - assets/images/products/
    - assets/images/categories/
    - assets/icons/
    - assets/fonts/cairo/